### ISSUE TITLE
Add restriction on EUDM category

### ISSUE THREAD

**Issue by nicholascar** [CSIRO-enviro-informatics/eudm-profile#2]
Can you add another restriction to Dataset of the form 

```
  rdfs:subClassOf [
      rdf:type owl:Restriction ;
      owl:minCardinality "1"^^xsd:nonNegativeInteger ;
      owl:onProperty eudm:hasEUDMcategory ;
] ;
```
where EUDM category is one of the individuals here: https://eudm.csiro.au/categories

Sally still needs to make this a vocab so you should be able to lock that on to one of the 10 individuals or one from the Collection of 10 Concepts, up to you to work out with her! I prefer the pure SKOS way here as they are clearly categories that could be used outside the EUDM profile.

**Comment by dr-shorthair** [comment]
I made a sub-class of skos:Concept called eudm:EUDMcategory and added the OWL and SHACL constraints
